linters-settings:
  govet:
    check-shadowing: false
  gocritic:
    color: true
    shorterErrLocation: true
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - hugeParam
      - singleCaseSwitch

linters:
  enable:
    - golint
    - megacheck
    - interfacer
    - unconvert
    - goconst
    - misspell
    - unparam
    - gofmt
    - goimports
    - gocyclo
    - gocritic
    - govet
    - unused
    - prealloc
    - bodyclose
    - whitespace

  disable:
    - errcheck

issues:
  exclude-use-default: false
  max-same-issues: 10
