version: '3'
services:
#  postgresql:
#    image: postgres:13-alpine
#    restart: always
#    container_name: postgresql
#    env_file: .env
#    hostname: "postgresql.local"
#    ports:
#      - 5432:5432
#    volumes:
#      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./data:/var/lib/postgresql/data/

  rabbitmq:
    image: rabbitmq:3.9
    restart: always
    container_name: rabbitmq
    ports:
      - 5672:5672 # AMQP protocol port
      - 15672:15672 # HTTP management UI
    volumes:
      - ./docker-conf/rabbitmq/data/:/var/lib/rabbitmq/

  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    container_name: api
    hostname: "api.local"
    ports:
      - 8080:8080
    env_file: .env
    restart: always
    depends_on:
#      - postgresql
      - rabbitmq

  converter:
    build:
      context: .
      dockerfile: Dockerfile-converter
    container_name: converter
    hostname: "converter.local"
    env_file: .env
    restart: always
    depends_on:
      - api
#      - postgresql
      - rabbitmq

volumes:
#  postgresql:
#    driver: local
  database-data: