version: '3'
services:

  api:
    image: public.ecr.aws/v1d6i5g3/converter-api-repo:v0.2
    container_name: api
    hostname: "api.local"
    env_file: .env
    restart: always
    ports:
      - 8080:8080

  converter:
    image: public.ecr.aws/v1d6i5g3/converter-worker-repo:v0.2
    container_name: converter
    hostname: "converter.local"
    env_file: .env
    restart: always
    depends_on:
      - api