name: Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Lint code
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29

      - name: Test
        run: go test ./..