name: CI/CD

on:
  push:

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest

      - name: Test
        run: go test ./...

#  build:
#    runs-on: ubuntu-latest
#    needs: lint_and_test
#    steps:
#      - name: Checkout master
#        uses: actions/checkout@v2
#
#      - name: Run docker-compose
#        run: docker-compose up -d