name: CI/CD

on:
  push:

jobs:
  lint_and_test:
    name: Lint and test the code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v2

      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest

      - name: Test
        run: go test ./...

#  build:
#    name: Build Docker image
#    needs: lint_and_test
#    runs-on: ubuntu-latest
#    timeout-minutes: 10
#    steps:
#      - name: Checkout master
#        uses: actions/checkout@v2
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#
#      - name: Build containers
#        run: docker-compose -f "docker-compose.yml" build